import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import HomeHero from "../components/HomeHero";
import Menu from "../components/Menu";
import Skill from "../components/Skills";
import WorkExperience from "../components/WorkExperience";
import WorkGrid from "../components/WorkGrid";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Terry&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className="container mx-auto flex flex-col gap-4 max-w-6xl px-4">
        <HomeHero />
        <Skill />
        <WorkExperience />
        <WorkGrid />
        <button className="font-semibold underline">Back to Top</button>
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
